"""add reading history and user library

Revision ID: 22255c9903d5
Revises: 6506bae6d7c9
Create Date: 2025-08-14 21:13:40.320440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22255c9903d5'
down_revision = '6506bae6d7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('read_count', sa.Integer(), nullable=False),
    sa.Column('first_read_at', sa.DateTime(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_type', 'content_id', name='uq_user_content_reading')
    )
    with op.batch_alter_table('reading_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_history_user_id'), ['user_id'], unique=False)

    op.create_table('user_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_type', 'content_id', name='uq_user_content_library')
    )
    with op.batch_alter_table('user_library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_library_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ad_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewable_impressions', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_stats', schema=None) as batch_op:
        batch_op.drop_column('viewable_impressions')

    with op.batch_alter_table('user_library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_library_user_id'))

    op.drop_table('user_library')
    with op.batch_alter_table('reading_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_history_user_id'))

    op.drop_table('reading_history')
    # ### end Alembic commands ###
