"""Initial migration for all models

Revision ID: 6506bae6d7c9
Revises: 
Create Date: 2025-08-06 20:01:39.175002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6506bae6d7c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('homepage_design', sa.String(length=50), nullable=True),
    sa.Column('logo_header', sa.String(length=255), nullable=True),
    sa.Column('logo_footer', sa.String(length=255), nullable=True),
    sa.Column('favicon', sa.String(length=255), nullable=True),
    sa.Column('placeholder_image', sa.String(length=255), nullable=True),
    sa.Column('enable_comments', sa.Boolean(), nullable=False, server_default=sa.text('1')),
    sa.Column('enable_ratings', sa.Boolean(), nullable=False, server_default=sa.text('1')),
    sa.Column('enable_ads', sa.Boolean(), nullable=False, server_default=sa.text('1')),
    sa.Column('enable_campaigns', sa.Boolean(), nullable=False, server_default=sa.text('1')),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contact_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon_class', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_detail_section_order'), ['section_order'], unique=False)

    op.create_table('custom_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media_guideline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_guideline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_guideline_section_order'), ['section_order'], unique=False)

    op.create_table('pedoman_hak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedoman_hak', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedoman_hak_section_order'), ['section_order'], unique=False)

    op.create_table('penyangkalan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penyangkalan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penyangkalan_section_order'), ['section_order'], unique=False)

    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('privacy_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('privacy_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_privacy_policy_section_order'), ['section_order'], unique=False)

    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('member_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_member_member_order'), ['member_order'], unique=False)

    op.create_table('visi_misi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visi_misi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visi_misi_section_order'), ['section_order'], unique=False)

    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['custom_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPERUSER', 'ADMIN', 'GENERAL', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('suspension_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('custom_role_id', sa.Integer(), nullable=True),
    sa.Column('has_premium_access', sa.Boolean(), nullable=False),
    sa.Column('premium_expires_at', sa.DateTime(), nullable=True),
    sa.Column('ad_preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['custom_role_id'], ['custom_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('ad_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_campaign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_campaign_is_active'), ['is_active'], unique=False)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], name='fk_comment_parent_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_comment_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_is_approved'), ['is_approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_is_spam'), ['is_spam'], unique=False)

    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath'),
    sa.UniqueConstraint('url')
    )
    op.create_table('navigation_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_navigation_link_user_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_rating_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_type', 'content_id', name='uq_user_content_rating')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_content_type'), ['content_type'], unique=False)

    op.create_table('root_seo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_identifier', sa.String(length=50), nullable=False),
    sa.Column('page_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('og_title', sa.String(length=200), nullable=True),
    sa.Column('og_description', sa.String(length=500), nullable=True),
    sa.Column('og_image', sa.String(length=255), nullable=True),
    sa.Column('og_type', sa.String(length=50), nullable=True),
    sa.Column('twitter_card', sa.String(length=50), nullable=True),
    sa.Column('twitter_title', sa.String(length=200), nullable=True),
    sa.Column('twitter_description', sa.String(length=500), nullable=True),
    sa.Column('twitter_image', sa.String(length=255), nullable=True),
    sa.Column('canonical_url', sa.String(length=255), nullable=True),
    sa.Column('meta_author', sa.String(length=100), nullable=True),
    sa.Column('meta_language', sa.String(length=10), nullable=True),
    sa.Column('meta_robots', sa.String(length=50), nullable=True),
    sa.Column('structured_data_type', sa.String(length=50), nullable=True),
    sa.Column('schema_markup', sa.Text(), nullable=True),
    sa.Column('google_analytics_id', sa.String(length=50), nullable=True),
    sa.Column('facebook_pixel_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('root_seo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_root_seo_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_root_seo_page_identifier'), ['page_identifier'], unique=True)

    op.create_table('social_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('payment_provider', sa.String(length=50), nullable=True),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(length=11), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_youtube_video_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    with op.batch_alter_table('youtube_video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_youtube_video_youtube_id'), ['youtube_id'], unique=True)

    op.create_table('ad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ad_type', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_alt', sa.String(length=200), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('external_ad_code', sa.Text(), nullable=True),
    sa.Column('external_ad_client', sa.String(length=100), nullable=True),
    sa.Column('external_ad_slot', sa.String(length=100), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('css_classes', sa.String(length=500), nullable=True),
    sa.Column('inline_styles', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaign.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_ad_type'), ['ad_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_is_active'), ['is_active'], unique=False)

    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_hiatus', sa.Boolean(), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('total_reads', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('og_title', sa.String(length=200), nullable=True),
    sa.Column('og_description', sa.String(length=500), nullable=True),
    sa.Column('og_image', sa.String(length=255), nullable=True),
    sa.Column('canonical_url', sa.String(length=255), nullable=True),
    sa.Column('seo_slug', sa.String(length=255), nullable=True),
    sa.Column('schema_markup', sa.Text(), nullable=True),
    sa.Column('twitter_card', sa.String(length=50), nullable=True),
    sa.Column('twitter_title', sa.String(length=200), nullable=True),
    sa.Column('twitter_description', sa.String(length=500), nullable=True),
    sa.Column('twitter_image', sa.String(length=255), nullable=True),
    sa.Column('meta_author', sa.String(length=100), nullable=True),
    sa.Column('meta_language', sa.String(length=10), nullable=True),
    sa.Column('meta_robots', sa.String(length=50), nullable=True),
    sa.Column('structured_data_type', sa.String(length=50), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('last_seo_audit', sa.DateTime(), nullable=True),
    sa.Column('is_seo_lock', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_album_category_id'),
    sa.ForeignKeyConstraint(['cover_image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_album_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_is_completed'), ['is_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_is_hiatus'), ['is_hiatus'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_is_premium'), ['is_premium'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_is_visible'), ['is_visible'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_seo_slug'), ['seo_slug'], unique=True)

    op.create_table('comment_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='fk_comment_like_comment_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_comment_like_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'comment_id', name='uq_user_comment_like')
    )
    op.create_table('comment_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='fk_comment_report_comment_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], name='fk_comment_report_resolved_by'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_comment_report_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_report_is_resolved'), ['is_resolved'], unique=False)

    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tagar', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('read_count', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_main_news', sa.Boolean(), nullable=False),
    sa.Column('is_news', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('writer', sa.String(length=100), nullable=True),
    sa.Column('external_source', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('og_title', sa.String(length=200), nullable=True),
    sa.Column('og_description', sa.String(length=500), nullable=True),
    sa.Column('og_image', sa.String(length=255), nullable=True),
    sa.Column('canonical_url', sa.String(length=255), nullable=True),
    sa.Column('seo_slug', sa.String(length=255), nullable=True),
    sa.Column('schema_markup', sa.Text(), nullable=True),
    sa.Column('twitter_card', sa.String(length=50), nullable=True),
    sa.Column('twitter_title', sa.String(length=200), nullable=True),
    sa.Column('twitter_description', sa.String(length=500), nullable=True),
    sa.Column('twitter_image', sa.String(length=255), nullable=True),
    sa.Column('meta_author', sa.String(length=100), nullable=True),
    sa.Column('meta_language', sa.String(length=10), nullable=True),
    sa.Column('meta_robots', sa.String(length=50), nullable=True),
    sa.Column('structured_data_type', sa.String(length=50), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('last_seo_audit', sa.DateTime(), nullable=True),
    sa.Column('is_seo_lock', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_news_category_id'),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name='fk_news_image_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_news_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_is_main_news'), ['is_main_news'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_is_news'), ['is_news'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_is_premium'), ['is_premium'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_is_visible'), ['is_visible'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_seo_slug'), ['seo_slug'], unique=True)

    op.create_table('ad_placement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('page_type', sa.String(length=100), nullable=False),
    sa.Column('page_specific', sa.String(length=200), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('position_value', sa.Integer(), nullable=True),
    sa.Column('max_ads_per_page', sa.Integer(), nullable=False),
    sa.Column('rotation_type', sa.String(length=50), nullable=False),
    sa.Column('display_frequency', sa.Float(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('location_targeting', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ad.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_placement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_placement_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_placement_page_type'), ['page_type'], unique=False)

    op.create_table('ad_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unique_users', sa.Integer(), nullable=False),
    sa.Column('returning_users', sa.Integer(), nullable=False),
    sa.Column('desktop_impressions', sa.Integer(), nullable=False),
    sa.Column('mobile_impressions', sa.Integer(), nullable=False),
    sa.Column('tablet_impressions', sa.Integer(), nullable=False),
    sa.Column('country_impressions', sa.JSON(), nullable=True),
    sa.Column('city_impressions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ad.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id', 'date', 'hour', name='uq_ad_stats_ad_date_hour')
    )
    with op.batch_alter_table('ad_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_stats_date'), ['date'], unique=False)

    op.create_table('album_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('chapter_title', sa.String(length=200), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('og_title', sa.String(length=200), nullable=True),
    sa.Column('og_description', sa.String(length=500), nullable=True),
    sa.Column('og_image', sa.String(length=255), nullable=True),
    sa.Column('canonical_url', sa.String(length=255), nullable=True),
    sa.Column('seo_slug', sa.String(length=255), nullable=True),
    sa.Column('schema_markup', sa.Text(), nullable=True),
    sa.Column('twitter_card', sa.String(length=50), nullable=True),
    sa.Column('twitter_title', sa.String(length=200), nullable=True),
    sa.Column('twitter_description', sa.String(length=500), nullable=True),
    sa.Column('twitter_image', sa.String(length=255), nullable=True),
    sa.Column('meta_author', sa.String(length=100), nullable=True),
    sa.Column('meta_language', sa.String(length=10), nullable=True),
    sa.Column('meta_robots', sa.String(length=50), nullable=True),
    sa.Column('structured_data_type', sa.String(length=50), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('last_seo_audit', sa.DateTime(), nullable=True),
    sa.Column('is_seo_lock', sa.Boolean(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], name='fk_album_chapter_album_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name='fk_album_chapter_news_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('album_chapter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_chapter_is_visible'), ['is_visible'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_chapter_seo_slug'), ['seo_slug'], unique=True)

    op.create_table('share_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_count', sa.Integer(), nullable=False),
    sa.Column('facebook_count', sa.Integer(), nullable=False),
    sa.Column('twitter_count', sa.Integer(), nullable=False),
    sa.Column('instagram_count', sa.Integer(), nullable=False),
    sa.Column('bluesky_count', sa.Integer(), nullable=False),
    sa.Column('clipboard_count', sa.Integer(), nullable=False),
    sa.Column('first_shared_at', sa.DateTime(), nullable=True),
    sa.Column('latest_shared_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share_log')
    with op.batch_alter_table('album_chapter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_chapter_seo_slug'))
        batch_op.drop_index(batch_op.f('ix_album_chapter_is_visible'))

    op.drop_table('album_chapter')
    with op.batch_alter_table('ad_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_stats_date'))

    op.drop_table('ad_stats')
    with op.batch_alter_table('ad_placement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_placement_page_type'))
        batch_op.drop_index(batch_op.f('ix_ad_placement_is_active'))

    op.drop_table('ad_placement')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_seo_slug'))
        batch_op.drop_index(batch_op.f('ix_news_is_visible'))
        batch_op.drop_index(batch_op.f('ix_news_is_premium'))
        batch_op.drop_index(batch_op.f('ix_news_is_news'))
        batch_op.drop_index(batch_op.f('ix_news_is_main_news'))
        batch_op.drop_index(batch_op.f('ix_news_is_archived'))
        batch_op.drop_index(batch_op.f('ix_news_date'))

    op.drop_table('news')
    with op.batch_alter_table('comment_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_report_is_resolved'))

    op.drop_table('comment_report')
    op.drop_table('comment_like')
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_seo_slug'))
        batch_op.drop_index(batch_op.f('ix_album_is_visible'))
        batch_op.drop_index(batch_op.f('ix_album_is_premium'))
        batch_op.drop_index(batch_op.f('ix_album_is_hiatus'))
        batch_op.drop_index(batch_op.f('ix_album_is_completed'))
        batch_op.drop_index(batch_op.f('ix_album_is_archived'))

    op.drop_table('album')
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_is_active'))
        batch_op.drop_index(batch_op.f('ix_ad_ad_type'))

    op.drop_table('ad')
    with op.batch_alter_table('youtube_video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtube_video_youtube_id'))

    op.drop_table('youtube_video')
    op.drop_table('user_subscriptions')
    op.drop_table('user_activity')
    op.drop_table('social_media')
    with op.batch_alter_table('root_seo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_root_seo_page_identifier'))
        batch_op.drop_index(batch_op.f('ix_root_seo_is_active'))

    op.drop_table('root_seo')
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_content_type'))
        batch_op.drop_index(batch_op.f('ix_rating_content_id'))

    op.drop_table('rating')
    op.drop_table('navigation_link')
    op.drop_table('image')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_is_spam'))
        batch_op.drop_index(batch_op.f('ix_comment_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_comment_is_approved'))
        batch_op.drop_index(batch_op.f('ix_comment_content_type'))
        batch_op.drop_index(batch_op.f('ix_comment_content_id'))

    op.drop_table('comment')
    with op.batch_alter_table('ad_campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_campaign_is_active'))

    op.drop_table('ad_campaign')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('role_permission')
    with op.batch_alter_table('visi_misi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visi_misi_section_order'))

    op.drop_table('visi_misi')
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_member_order'))

    op.drop_table('team_member')
    with op.batch_alter_table('privacy_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_privacy_policy_section_order'))

    op.drop_table('privacy_policy')
    op.drop_table('permission')
    with op.batch_alter_table('penyangkalan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penyangkalan_section_order'))

    op.drop_table('penyangkalan')
    with op.batch_alter_table('pedoman_hak', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedoman_hak_section_order'))

    op.drop_table('pedoman_hak')
    with op.batch_alter_table('media_guideline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_guideline_section_order'))

    op.drop_table('media_guideline')
    op.drop_table('custom_role')
    with op.batch_alter_table('contact_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_detail_section_order'))

    op.drop_table('contact_detail')
    op.drop_table('category')
    op.drop_table('brand_identity')
    # ### end Alembic commands ###
